title: "Brett Landau's Blog"
author: "Brett Landau"
email: "brett@landau.xyz"
description: "My personal blog."
baseurl: ""
url: "https://brett.landau.xyz"

# No theme, we are using custom layout
theme:
plugins: []
